### ISSUE TITLE
Java Home can not be manually set during package CHECK

### ISSUE THREAD

**Issue by javadch** [javadch/rquis#15]
It is hard to set the JAVA_HOME, JRE_JOME, and PATH variables required for the package to function properly. Would be good if it is done transparently.

**Comment by javadch** [comment]
I have changed the relative folders of ex1.xqt, ex2.xqt, and RQtTest2.R from extdata\ to inst\extdata\, to be able to run the tests and validate the issue #15 is fixed.

**Comment by javadch** [comment]
When I am using the SciQuest IDE, it fails to automatically find the JDK, so reopened!

**Comment by javadch** [comment]
@ClaytonJY if you pass the R checks, close (or let me know to) this issue #15

**Comment by ClaytonJY** [comment]
@javadch I don't, I still can't run the function-doc examples:

```
* checking examples ... ERROR
Running examples in ‘RQt-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: rqt.addScript
> ### Title: Adds one or more statements to the current process.
> ### Aliases: rqt.addScript
> 
> ### ** Examples
> 
> engine1 <- rqt.getEngine()
Error in .jnew("xqt/api/LanguageServicePoint", "RQt, RQt\\inst, inst") : 
  java.lang.UnsupportedClassVersionError: xqt/api/LanguageServicePoint : Unsupported major.minor version 52.0
Calls: rqt.getEngine -> .jnew -> .External
Execution halted
```

This may be related to #11 as well.

**Comment by javadch** [comment]
I cannot reproduce it, could you send me the result of the following command plus the log file generated in RQtcheck\logs\
On windows: where javac
On linux: wehereis javac
On mac: which javac

**Comment by ClaytonJY** [comment]
I'm running Linux, and I get this:

```
cyochum@clayton-XPS:~/github/JavadCH/RQt > whereis javac
javac: /usr/bin/javac /usr/bin/X11/javac /usr/share/man/man1/javac.1.gz
```

I do not have a folder `RQt.Rcheck/logs/`; there is `00check.log`, the relevant section of which I pasted above, and `Rdlatex.log`, which is just about building the manual.

**Comment by javadch** [comment]
Would you check whether JDK is installed in one of those locations and is 1.8.x. when the RQt.Rcheck\logs\ is not created or empty, usually means JDK is not found.

**Comment by ClaytonJY** [comment]
So I was on JDK 1.7 (OpenJDK 7), but used instructions [here](http://ubuntuhandbook.org/index.php/2015/01/install-openjdk-8-ubuntu-14-04-12-04-lts/#comments) to install OpenJDK 8 and set it as my default:

```
cyochum@clayton-XPS:~/github/JavadCH/RQt > java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
```

The first return from `whereis javac`, `/usr/bin/java`, is a series of symlinks which now terminate at `/usr/lib/jvm/java-8-openjdk-amd64/bin/javac`, so it does seem to be using the correct version now.

After all this, I still get the same error in `R CMD check` as before, and no `logs/` folder.

**Comment by javadch** [comment]
Then I have to double check the JDK search algorithm and need a physical
meeting with you to closely test it on the Linux box.

**Comment by ClaytonJY** [comment]
So I just happened to remember that `sudo R CMD javareconf` is a thing, and when I ran it noticed it was still using 1.7. I had to update another symlink to point to 1.8 instead, re-ran the command, and now I get a new `R CMD check` error:

```
* checking examples ... ERROR
Running examples in ‘RQt-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: rqt.getVariable
> ### Title: Gets the resultset by variable name.
> ### Aliases: rqt.getVariable
> 
> ### ** Examples
> 
> engine1 <- rqt.getEngine()
> rqt.loadProcess(engine1, system.file("Examples/processes", "ex2.xqt", package="RQt"))
[1] "OK. Process file /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt/Examples/processes/ex2.xqt was registered. All previous statements were cleared. \n"
> rqt.runProcess(engine1)
[1] "**************************************************************************************\n******************************* Synatx and Semantic Errors *******************************\n**************************************************************************************\n**************************************************************************************\n****************************** Statement Execution Results ********************************\n**************************************************************************************\nStatement 1 was NOT executed.\n"
> dlm <- rqt.getVariable(engine1, "meanDailyTemp")
Error in .jevalArray(data) : 
  object is not a Java object reference (jobjRef/jarrayRef).
Calls: rqt.getVariable -> as.data.frame -> lapply -> .jevalArray
Execution halted
```

I also now have `RQt.Rcheck/logs/log.log`:

```
2015-08-21 11:39:30 DEBUG - The system API is initiated using config folders: RQt, RQt\inst, inst.
 2015-08-21 11:39:30 DEBUG - The system API is initiated at the root folder: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/..
 2015-08-21 11:39:30 DEBUG - The system API is initiated using config folders: RQt, RQt\inst, inst.
 2015-08-21 11:39:30 DEBUG - The system API is initiated at the root folder: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/..
 2015-08-21 11:39:30 DEBUG - Searching config/adapters.xml for adapter configuration.
 2015-08-21 11:39:30 DEBUG - Searching RQt/config/adapters.xml for adapter configuration.
 2015-08-21 11:39:30 DEBUG - Loading file /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt/config/adapters.xml
 2015-08-21 11:39:31 DEBUG - The adapter config file /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt/config/adapters.xml was successfully loaded.
 2015-08-21 11:39:31 DEBUG - The system API is initiated using config folders: RQt, RQt\inst, inst.
 2015-08-21 11:39:31 DEBUG - The system API is initiated at the root folder: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/..
 2015-08-21 11:39:31 DEBUG - The system API is initiated using config folders: RQt, RQt\inst, inst.
 2015-08-21 11:39:31 DEBUG - The system API is initiated at the root folder: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/..
 2015-08-21 11:39:31 DEBUG - The system API is initiated using config folders: RQt, RQt\inst, inst.
 2015-08-21 11:39:31 DEBUG - The system API is initiated at the root folder: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/..
 2015-08-21 11:39:31 DEBUG - Initilizing the execution engine...
 2015-08-21 11:39:31 DEBUG - Loading function specifications...
 2015-08-21 11:39:31 DEBUG - Searching config/adapters.xml for adapter configuration.
 2015-08-21 11:39:31 DEBUG - Searching RQt/config/adapters.xml for adapter configuration.
 2015-08-21 11:39:31 DEBUG - Function specifications loaded
 2015-08-21 11:39:31 DEBUG - Query engine is built and ready to be used.
 2015-08-21 11:39:31 DEBUG - execution of the process is started.
 2015-08-21 11:39:31 DEBUG - The exeution engine is loading adapter: CSV from file:/xqt.adapters.csv-1.0-SNAPSHOT.jar.
 2015-08-21 11:39:31 DEBUG - Class loader is instantiated for adapter: CSV from file:/xqt.adapters.csv-1.0-SNAPSHOT.jar.
 2015-08-21 11:39:31 DEBUG - Adapter class definition is loaded for adapter: CSV from file:/xqt.adapters.csv-1.0-SNAPSHOT.jar.
 2015-08-21 11:39:31 DEBUG - The CSV adapter encapsulated in the class: xqt.adapters.csv.CsvDataAdapter was successfully instantiated.
 2015-08-21 11:39:31 DEBUG - Adapter class is instantiated for adapter: CSV from file:/xqt.adapters.csv-1.0-SNAPSHOT.jar.
 2015-08-21 11:39:31 DEBUG - The CSV adapter located at file:/xqt.adapters.csv-1.0-SNAPSHOT.jar was successfully loaded.
 2015-08-21 11:39:31 DEBUG - The CSV adapter started preparing statement 1
 2015-08-21 11:39:31 DEBUG - The CSV adapter is extracting the fields from file: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt\\extdata\\fso2014h.csv.hdr 
 2015-08-21 11:39:31 ERROR - Schema generation error for adapter: CSV. /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt\\extdata\\fso2014h.csv.hdr (No such file or directory)
 2015-08-21 11:39:31 DEBUG - Searching config/adapters.xml for adapter configuration.
 2015-08-21 11:39:31 DEBUG - Searching RQt/config/adapters.xml for adapter configuration.
 2015-08-21 11:39:31 ERROR - An exception has occured in the DefaultQueryEngine. execute method. Details: null.
 2015-08-21 11:39:31 DEBUG - execution of the process is finished.
 2015-08-21 11:39:31 ERROR - **************************************************************************************
******************************* Synatx and Semantic Errors *******************************
**************************************************************************************
**************************************************************************************
****************************** Statement Execution Results ********************************
**************************************************************************************
Statement 1 was NOT executed.

 2015-08-21 11:39:31 DEBUG - The system API is initiated using config folders: RQt, RQt\inst, inst.
 2015-08-21 11:39:31 DEBUG - The system API is initiated at the root folder: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/..
 2015-08-21 11:39:31 DEBUG - Initilizing the execution engine...
 2015-08-21 11:39:31 DEBUG - Loading function specifications...
 2015-08-21 11:39:31 DEBUG - Function specifications loaded
 2015-08-21 11:39:31 DEBUG - Query engine is built and ready to be used.
 2015-08-21 11:39:31 DEBUG - execution of the process is started.
 2015-08-21 11:39:31 DEBUG - The exeution engine is loading adapter: CSV from file:/xqt.adapters.csv-1.0-SNAPSHOT.jar.
 2015-08-21 11:39:31 DEBUG - Class loader is instantiated for adapter: CSV from file:/xqt.adapters.csv-1.0-SNAPSHOT.jar.
 2015-08-21 11:39:31 DEBUG - Adapter class definition is loaded for adapter: CSV from file:/xqt.adapters.csv-1.0-SNAPSHOT.jar.
 2015-08-21 11:39:31 DEBUG - The CSV adapter encapsulated in the class: xqt.adapters.csv.CsvDataAdapter was successfully instantiated.
 2015-08-21 11:39:31 DEBUG - Adapter class is instantiated for adapter: CSV from file:/xqt.adapters.csv-1.0-SNAPSHOT.jar.
 2015-08-21 11:39:31 DEBUG - The CSV adapter located at file:/xqt.adapters.csv-1.0-SNAPSHOT.jar was successfully loaded.
 2015-08-21 11:39:31 DEBUG - The CSV adapter started preparing statement 1
 2015-08-21 11:39:31 DEBUG - The CSV adapter is extracting the fields from file: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt\\extdata\\fso2014h.csv.hdr 
 2015-08-21 11:39:31 ERROR - Schema generation error for adapter: CSV. /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt\\extdata\\fso2014h.csv.hdr (No such file or directory)
 2015-08-21 11:39:31 ERROR - An exception has occured in the DefaultQueryEngine. execute method. Details: null.
 2015-08-21 11:39:31 DEBUG - execution of the process is finished.
 2015-08-21 11:39:31 ERROR - **************************************************************************************
******************************* Synatx and Semantic Errors *******************************
**************************************************************************************
**************************************************************************************
****************************** Statement Execution Results ********************************
**************************************************************************************
Statement 1 was NOT executed.
```

**Comment by javadch** [comment]
The first issue could be these double back-slashes in the file name:
/mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt\extdata\fso2014h.csv.hdr
which should be here: /mnt/bigdisk/claytonjy/github/JavadCH/RQt.Rcheck/RQt/
Examples/processes/ex2.xqt

Also the log file misses some records, related loading of the config
folder. I go through it.

**Comment by ClaytonJY** [comment]
I see what you mean; it seems to me the java code related to the CSV adapter must be building paths in a non-platform-independent way?

Remember it shouldn't be `Examples/processes` as we got rid of those directories; the path is essentially correct, just using the wrong separators.

**Comment by javadch** [comment]
Yes, for now it is the wrong separator. but I am dealing with a potential
JDK location finding issue (for Linux), which I am working on :-(

**Comment by javadch** [comment]
I found an issue with JDK path extraction for and fixed it on the XQt Java code. will create a java-Home branch on RQt, apply the fix and create a PR.

**Comment by ClaytonJY** [comment]
I think this issue has been covered.
